export const APP_NAME  = "JUST KEEP SWIMMING"
export const SETTINGS = "SETTINGS"
export const PAUSED = "PAUSED"
export const PLAY = "PLAY"
export const GAME_OVER = "GAME OVER"
export const INFO = "INFO"